format: 0.1.0
stages:
  ipfs_deploy:
    package: ipfs
    uri: fs/./build
  from_deploy:
    package: local-dev-ens
    depends_on: ipfs_deploy
    config:
      domainName: polywrap.substrate.eth
      ports:
        ethereum: 8545
