name: Publish-Substrate-Docker

on:
  push:
    branches:
    - main
    paths:
    - 'protocol/substrate/test-env/**'

jobs:
  Publish:
    name: Substrate Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image and push GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./protocol/substrate/test-env
          tags: |
            ghcr.io/chainsafe/integrations/substrate-polywrap-test-env:latest
